-- Snell 的共享凭据模式(V14.1)。
--
-- 加它的理由只有一条,而且是被客户端逼出来的:**mihomo 的 snell proxy
-- 没有用户凭据那一栏**(`adapter/outbound/snell.go` 里只有 psk),它写进请求的
-- client-id 长度恒为 0。而 sing-box 的 snell 入站只要 `users` 非空就走多用户,
-- 多用户一律按 client-id 查表 —— 于是 mihomo 连多用户入口必然拿到
-- `snell: bad user key`。真机实测过。
--
-- 也就是说:**要让 Clash / mihomo 那一支用上 Snell,就只能不下发 users。**
-- 那时 sing-box 用 `NewService` 而不是 `MultiService`,服务端根本不读 client-id,
-- 所有人共用顶层那一个 psk。
--
-- ---------- 这一列存在的意义是把"静默"变成"显式" ----------
--
-- 迁移 0030 的注释里写着:users 渲染成空列表会让入口静默退回单用户模式,
-- 而 psk 就在每个用户的客户端配置里 —— 于是每一个拿到过 psk 的人
-- (包括刚被移出的那个)照常连得上,没有计量、没有办法撤销,面板一个字都不说。
-- 那条规矩一个字都不改:`singbox.ErrSnellNoUsers` 仍然拦住"多用户模式下
-- 一个用户都没有"。
--
-- 这一列的作用是让同一个渲染结果有两种来源,而两者的**区别不在配置里、
-- 在面板里**:一种是管理员看着代价按下去的开关,另一种是谁都没注意到的空列表。
-- 有了它,渲染期就能分辨"这是他要的"和"这是出事了"。
--
-- ---------- 代价(界面上必须逐条列出来)----------
--
--   * 这个入口**没有分用户流量** —— sing-box 不会为它建 user 计数器。
--     节点级的量还有(inbound>>> 计数器在单用户模式下照常工作,实测
--     2,097,152 字节的下载记到 2,106,248),面板按它记节点用量,
--     所以商家额度那一侧不会静默少算;
--   * **撤销一个人 = 换掉这个入口的 psk = 所有人一起断**。
--     多用户模式下把人从列表里去掉就行,这里做不到;
--   * 用户额度对它不生效 —— 额度是按用户算的,而这个入口分不出用户。
--
-- ---------- 为什么共享模式强制版本 5 ----------
--
-- 共享模式**唯一的理由**是让 mihomo 能用,而 mihomo 只支持 snell v1~v5
-- (v5 内部按 v4 处理),对 `version: 6` 是**整份配置拒绝**:
-- `Parse config error: proxy 1: snell version error: 6` —— 一条坏 proxy
-- 会让那个用户丢掉订阅里的**全部**节点。所以"共享 + v6"这个组合
-- 既拿不到分用户流量、也用不了 mihomo,是一个只有代价没有好处的配置,
-- 由 `validateSnellParams` 拒掉。

ALTER TABLE node_inbounds ADD COLUMN snell_shared_psk INTEGER NOT NULL DEFAULT 0;

-- 节点上【当前正在生效】的那一份,只在部署成功时写入。
--
-- 必须有镜像列:管理员把一个入口从共享改成多用户、还没下发时,
-- 节点上跑的仍然是共享模式 —— 这时订阅要继续按共享下发(Clash 那份 proxy
-- 还是能用的)。按期望值下发的话,mihomo 用户会在部署之前就先断一次,
-- 而数据库、节点、面板三方都是"对的",只有订阅站在中间说了假话。
-- 与 deployed_snell_version 一字不差的理由。
ALTER TABLE node_inbounds ADD COLUMN deployed_snell_shared_psk INTEGER NOT NULL DEFAULT 0;
